export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const BETS_LOADING = "BETS_LOADING";
export const BETS_LOADED = "BETS_LOADED";
export const TODAYS_BETS_LOADED = "TODAYS_BETS_LOADED"

export const CHECKING_TODAYS_BETS = "CHECKING_TODAYS_BET"
export const FIXTURE_ERROR = "FIXTURE_ERROR"
export const TODAYS_BETS_SETTLED = "TODAYS_BETS_SETTLED"
export const SETTLING_OLD_BETS = 'SETTELING_UNSETTLED_BETS'
export const SETTELD_OLD_BETS = 'SETTELD_UNSETTLED_BETS'


export const BANK_ERROR = "BANK_ERROR";
export const BANK_UPDATED = "BANK_UPDATED";
export const UPDATING_BANK = "UPDATING_BANK";


export const BOOKIE_LOADING = "BOOKIE_LOADING";
export const BOOKIE_LOADED = "BOOKIE_LOADED";
export const BOOKIE_UPDATED = "BOOKIE_UPDATED";
export const UPDATING_BOOKIE = "UPDATING_BOOKIE";

export const EXCHANGE_LOADING = "EXCHANGE_LOADING";
export const EXCHANGE_LOADED = "EXCHANGE_LOADED";
export const UPDATING_EXCHANGE = "UPDATING_EXCHANGE";
export const EXCHANGE_UPDATED = "EXCHANGE_UPDATED";


export const WALLET_LOADING = "WALLET_LOADING";
export const WALLET_LOADED = "WALLET_LOADED";